import nao
nao.InitProxy(IP="10.0.0.5")
nao.InitPose()
nao.Say("I am happy")
nao.RunMovement("HappyGesture_1.py", post = False)
nao.RunMovement("HappyGesture_2.py", post = False)
nao.RunMovement("HappyGesture_3.py", post = False)
nao.RunMovement("HappyGesture_4.py", post = False)
nao.Say("I am sad")
nao.RunMovement("SadGesture_1.py", post = False)
nao.RunMovement("SadGesture_2.py", post = False)
nao.RunMovement("SadGesture_3.py", post = False)
nao.RunMovement("SadGesture_4.py", post = False)
nao.Say("I want your attention")
nao.RunMovement("AttentionGesture1_5.py", post = False)
nao.RunMovement("AttentionGesture2_5.py", post = False)
nao.Say("I have a question for you")
nao.RunMovement("QuestionGesture_1.py", post = False)
nao.RunMovement("QuestionGesture_2.py", post = False)
nao.RunMovement("QuestionGesture_3.py", post = False)
nao.RunMovement("QuestionGesture_4.py", post = False)
nao.Say("I don't know")
nao.RunMovement("DontKnowGesture_1.py", post = False)
nao.RunMovement("DontKnowGesture_2.py", post = False)
nao.RunMovement("DontKnowGesture_3.py", post = False)
nao.RunMovement("DontKnowGesture_4.py", post = False)
nao.Say("I want you to do something for me")
nao.RunMovement("CommandGesture_1.py", post = False)
nao.RunMovement("CommandGesture_2.py", post = False)
nao.RunMovement("CommandGesture_3.py", post = False)
nao.RunMovement("CommandGesture_4.py", post = False)

nao.Say("I am happy")
nao.RunLED("HappyLed_2.csv")
time.sleep(3)
nao.RunLED("HappyLed_5.csv")
time.sleep(6)
nao.Say("I am sad")
nao.RunLED("SadLed_2.csv")
time.sleep(3)
nao.RunLED("SadLed_5.csv")
time.sleep(6)
nao.Say("I am afraid")
nao.RunLED("FearLed_2.csv")
time.sleep(3)
nao.RunLED("FearLed_5.csv")
time.sleep(6)
nao.Say("I have a question for you")
nao.RunLED("QuestionLed_1.csv")
time.sleep(2)
nao.RunLED("QuestionLed_2.csv")
time.sleep(3)
nao.RunLED("QuestionLed_3.csv")
time.sleep(4)
nao.RunLED("QuestionLed_4.csv")
time.sleep(5)
nao.RunLED("QuestionLed_5.csv")
time.sleep(6)
nao.Say("I am neutral about that")
nao.RunLED("NeutralLed_2.csv")
time.sleep(3)
nao.RunLED("NeutralLed_5.csv")

nao.Crouch()




